### ISSUE TITLE
More videos

### ISSUE THREAD

**Issue by Nagapetyan** [dfreelon/pyktok#15]
Why do we have 15(30) videos limit. What should I do to download more videos?

**Comment by dfreelon** [comment]
Hi, the short answer is that late last year, TikTok shut down the endpoint that gave programmatic access to video feeds (e.g. from a specific user or search term). Longer answer here: https://github.com/dfreelon/pyktok/issues/6

**Comment by dfreelon** [comment]
Other ideas:

- If you have a list of users or hashtags, you can download up to 30 (users) or 15 (hashtags) for each one
- If you set up pyktok to trigger automatically using something like `cron`, you could have it download whatever appears on the page periodically (say, once every 12 or 24 hours)--this will probably work better with busy hashtag pages than with individual users who post once a day or less
