### ISSUE TITLE
Did TT break save video?

### ISSUE THREAD

**Issue by croweDF** [dfreelon/pyktok#19]
Great tool, the CSV listing it creates is really helpful. I was using this just Wednesday and downloading videos no problem, but today - no luck. Just wanted to check if you were aware of anything TT did that would break save video. Thanks.

**Comment by dfreelon** [comment]
Yep, looks like it--function is returning "Access Denied." Looking into it...

**Comment by dfreelon** [comment]
OK, now I can't view TT videos by themselves (i.e. without the surrounding comments, related videos etc. Can anyone else do this?

**Comment by dfreelon** [comment]
Well, using this site: https://savett.cc/en/ I figured out how to pull a working standalone TT URL, e.g. https://v39.tiktokcdn-us.com/df11acde2bc0d9d9ae2f365d1ea02390/63e6cf85/video/tos/useast5/tos-useast5-pve-0068-tx/60b8cdef3a584f7392bfa09a8d147bf7/?a=1233&amp;ch=0&amp;cr=3&amp;dr=0&amp;lr=all&amp;vr=all&amp;cd=0%7C0%7C0%7C3&amp;cv=1&amp;br=838&amp;bt=419&amp;cs=0&amp;ds=6&amp;ft=aEKfuqT0mIsPD12iDr9q3wU3cSfaEeF~OD&amp;mime_type=video_mp4&amp;qs=0&amp;rc=aGY3aGdlZDlmZWZnZzU3ZkBpM29scDc6ZnhkODMzNzczM0AvYS1iLl8vNi8xLjJiLjE0YSNlcGwucjRvMjRgLS1kMTZzcw%3D%3D&amp;l=202302101713048226E689EC529F0412DA&#34;

Problem is, this doesn't show up in the JSON, the rendered page, or among the XHR requests that I can see. Any ideas?

**Comment by croweDF** [comment]
I've used this site in the past as well: https://snaptik.app/

Sorry, friend, no ideas at the moment re: the JSON.

**Comment by dphiffer** [comment]
I tinkered a little bit but did not figure this out. Here are some things I tried, in case they might offer some clues:
- matched the request headers more closely to what I was seeing in my browser console (e.g., `Accept`)
- passed cookies with the video request
- looked at [how `youtube-dl` approaches this](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/tiktok.py), but then realized it was also failing to download

**Comment by dfreelon** [comment]
There's gotta be a way. If those TT download websites could figure it out, anyone can.

**Comment by vrocx28** [comment]
@dfreelon i figured out how to download the videos as of 3 march 2023 while i was working on a similar thing, i stumbled across your project right now, but i have no experience contributing to open source projects

**Comment by dfreelon** [comment]
Well, if you have working code or any other details that might help, feel free to share them...

**Comment by vrocx28** [comment]
> Well, if you have working code or any other details that might help, feel free to share them...

Yes, i have working code, but i am travelling currently, the new download url in the embedded json end with chain_tt_token which is set when we call any tiktok video, a simple fix would be to extract those cookies and pass those cookies in the header don't use cookies=cookies but update the header dict

**Comment by vrocx28** [comment]
> > @dfreelon i figured out how to download the videos as of 3 march 2023 while i was working on a similar thing, i stumbled across your project right now, but i have no experience contributing to open source projects
> 
> Hey, Vrocx can you describe how you solve this issue?

The new download url in the embedded json end with chain_tt_token which is set when we call any tiktok video, a simple fix would be to extract those cookies and pass those cookies in the header don't use cookies=cookies but update the header dict

**Comment by dfreelon** [comment]
This is now fixed; see https://github.com/dfreelon/pyktok/pull/22 . Big thx to @dphiffer !

**Comment by dphiffer** [comment]
I had tried passing cookies in my earlier testing but hadn't considered that the cookies would need refreshing. @vrocx28's comments got me to try that angle out again.
