### ISSUE TITLE
ImportError: cannot import name 'ChromeType' from 'webdriver_manager.core.utils'

### ISSUE THREAD

**Issue by XDavidT** [dfreelon/pyktok#25]
cannot import name 'ChromeType' from 'webdriver_manager.core.utils' (/Users/xdavidt/Documents/VCode/telegram_bots/.venv/lib/python3.9/site-packages/webdriver_manager/core/utils.py)
  File "/Users/xdavidt/Documents/VCode/telegram_bots/MediaBot/app/tiktok_v2.py", line 1, in <module>
    import pyktok as pyk
ImportError: cannot import name 'ChromeType' from 'webdriver_manager.core.utils' (/Users/xdavidt/Documents/VCode/telegram_bots/.venv/lib/python3.9/site-packages/webdriver_manager/core/utils.py)

Why is that?
The code is the example on the Readme

**Comment by dfreelon** [comment]
This has been fixed.
