### ISSUE TITLE
No module named 'webdriver_manager.core.os_manager' Error

### ISSUE THREAD

**Issue by 31onMusk** [dfreelon/pyktok#28]
I get this error:
Exception has occurred: ModuleNotFoundError
No module named 'webdriver_manager.core.os_manager'
  File "C:\Users\Elon Musk\TTD.py", line 1, in <module>
    import pyktok as pyk
ModuleNotFoundError: No module named 'webdriver_manager.core.os_manager'

Some ideas how to solve that?

**Comment by dfreelon** [comment]
What version are you using?

**Comment by 31onMusk** [comment]
I use pyktok 0.0.17 and webdriver-manager 4.0.1

**Comment by dfreelon** [comment]
What is the result of the following code?
```python
import webdriver_manager
webdriver_manager.__version__
```

**Comment by 31onMusk** [comment]
I get 3.8.2

**Comment by dfreelon** [comment]
Please upgrade to 4.0.1 and then try it. Will fix this permanently in the next update

**Comment by 31onMusk** [comment]
It's fixed, but now I get other error:

Exception has occurred: PermissionError
[Errno 13] Permission denied: 'C:\\Users\\Elon Musk\\AppData\\Roaming\\..\\Local\\Google\\Chrome\\User Data\\Default\\Network\\Cookies'
  File "C:\Users\Elon Musk\TTD.py", line 1, in <module>
    import pyktok as pyk
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Elon Musk\\AppData\\Roaming\\..\\Local\\Google\\Chrome\\User Data\\Default\\Network\\Cookies'
