### ISSUE TITLE
Exception has occurred: PermissionError

### ISSUE THREAD

**Issue by 31onMusk** [dfreelon/pyktok#29]
I get this error:
Exception has occurred: PermissionError
[Errno 13] Permission denied: 'C:\Users\Elon Musk\AppData\Roaming\..\Local\Google\Chrome\User Data\Default\Network\Cookies'
File "C:\Users\Elon Musk\TTD.py", line 1, in
import pyktok as pyk
PermissionError: [Errno 13] Permission denied: 'C:\Users\Elon Musk\AppData\Roaming\..\Local\Google\Chrome\User Data\Default\Network\Cookies'

Some ideas how to solve that?

**Comment by dfreelon** [comment]
Hi, I had that problem as well. This fixed it for me: https://stackoverflow.com/questions/76440733/unable-to-open-cookie-file

**Comment by 31onMusk** [comment]
Thanks! It works!
