### ISSUE TITLE
Remove "enter the name of a web browser" input

### ISSUE THREAD

**Issue by 31onMusk** [dfreelon/pyktok#30]
Is there a way to remove "Please enter the name of a web browser on your system (e.g. firefox, chrome, edge, etc.):" input in cmd?

**Comment by dfreelon** [comment]
No, the program won't work for many users without this. Basically, if any installed browser has its cookie access restricted, the browser-free option will fail. I have confirmed this is the case for Google Chrome and MS Edge, and it may apply to others as well.

**Comment by dfreelon** [comment]
If you have a better idea of how to supply the module a browser at import time, feel free to make a PR.
