### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by Rana0945** [dfreelon/pyktok#37]
I am trying to run that function specify_browser('chrome') but giving me PermissionError: [Errno 13] Permission denied: 'C:\Users\Usman\AppData\Roaming\..\Local\Google\Chrome\User Data\Default\Network\Cookies'
kindly help me to resolve that issue. I am stuck there after trying to resolve this issue

**Comment by dfreelon** [comment]
Please see https://github.com/dfreelon/pyktok/issues/20 and https://github.com/dfreelon/pyktok/issues/29
