### ISSUE TITLE
save_video parameter

### ISSUE THREAD

**Issue by timverbeij** [dfreelon/pyktok#52]
Thank you for this amazing module! It works perfectly on my Windows computer. I recently encountered an issue with the `save_video` parameter in the `save_tiktok` function (also with `save_tiktok_multi_urls`). Specifically, I only want to scrape the metadata to a large amount of TikTok videos, however the video is automatically downloaded as well even when I set the `save_video` to `False`. I  have tried different browsers (e.g., Edge) and Python versions (3.10, 3.11, and 3.12).

```
pk.save_tiktok(video_url=link,
save_video=False,
metadata_fn='metadata.csv',
browser_name='chrome')
```

Any help would be much appreciated!

**Comment by dfreelon** [comment]
OK, should work now if you upgrade. Thanks for the issue.

**Comment by timverbeij** [comment]
Thanks for the quick fix!
