### ISSUE TITLE
Expecting value: line 1 column 1 (char 0) issue with save_hashtag_video_urls()

### ISSUE THREAD

**Issue by yjqian02** [dfreelon/pyktok#6]
Thanks for all your hard work in this module! I've been using it to scrape TikTok videos by hashtag for a research study, but today when I try to run save_hashtag_video_urls() with any hashtag, I keep getting the following output:
```
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
```
and it keeps repeating. I'm still able to use the other functions, and I first noticed this issue around 12 pm CDT today. Would this be an issue with the TikTok API changing?

**Comment by JBGruber** [comment]
I think TikTok deprecated the search for hashtags functionality (or moved it). The entire endpoint is gone / returning 404: https://www.tiktok.com/tag/ 

I already have an issue over at the R package repo: https://github.com/JBGruber/traktok/issues/4

**Comment by dfreelon** [comment]
So the endpoint is not gone, I just checked. When I look at the following [API URL](https://us.tiktok.com/api/challenge/item_list/?aid=1988&app_language=en&app_name=tiktok_web&battery_info=0.91&browser_language=en-US&browser_name=Mozilla&browser_online=true&browser_platform=Win32&browser_version=5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F107.0.0.0%20Safari%2F537.36&challengeID=1702886133713926&channel=tiktok_web&cookie_enabled=true&count=30&cursor=0&device_id=7166228203346019883&device_platform=web_pc&focus_state=true&from_page=hashtag&history_len=3&is_fullscreen=false&is_page_visible=true&language=en&os=windows&priority_region=&referer=&region=US&screen_height=720&screen_width=1280&tz_name=America%2FNew_York&webcast_language=en&msToken=eF7P-ByID0ESKZ_NUNkUW2DHo_T90KeM92pNHHRRNNJ5wxUKsMiDyU8Lp23g6tUH9wPXIcR-7qCnBo3-vMF8OmYEb3jbQ6NyZxIIL9pBmUzfIDe7cHmSCi88Op-C0Gg=&X-Bogus=DFSzswVO0oJANGrzS8U1QOYklT6u&_signature=_02B4Z6wo00001EMWkqAAAIDBnWDKBmAwheBDFpYAAHO9a4), it delivers the expected data. This means TikTok has changed the required parameters to deliver a valid response, which means that someone needs to go through the URL params to figure out which ones are necessary. The earliest I'll be able to get to that is next week most likely, but @JBGruber if you have time this week, please LMK which parameters are required and I'll fix it ASAP.

**Comment by dfreelon** [comment]
Yeah, `/search/item/full` works for me and it's probably better generally as it can be used to retrieve stitched videos as well. I'll make the change when time permits...

**Comment by Jmallone** [comment]
@JBGruber and @dfreelon Same thing happened in this issue from another project: https://github.com/davidteather/TikTok-Api/issues/976#issuecomment-1316747795

Removing any of the parameters from `https://www.tiktok.com/api/challenge/item_list/` no longer returns anything

`https://www.tiktok.com/api/challenge/item_list/` still has the cursor but not the offset, I tried to change it and it still doesn't work, it seems that **__signature** has to change together or **msToken** and **X-Bogus**

Do you have any idea how to resolve this?

**Comment by Jmallone** [comment]
@dfreelon Awsome
 I was using `/challenge/item_list/` to get videos from hashtags, does `/search/item/full/` do the same thing?

**Comment by dfreelon** [comment]
I think so--we use a two-step process to pull video URLs from `search` using one function and get the videos themselves applying a second function to those URLs. You could at least follow a similar approach.

**Comment by JBGruber** [comment]
I've got a working wrapper for it now over at the R package.  I was able to cut down the api call quite a bit. You can search for users, hashtags or just keywords without specifying anything. This seems to be an improvement for data access:

https://github.com/JBGruber/traktok/blob/a64b9e585b55831690661685e9408ee186f3a4c9/R/traktok.R#L357-L366

Essentially, A url would read like this for a user: `https://www.tiktok.com/api/search/item/full/?keyword=%40chilipeppers&offset=0`

For a hashtag: `https://www.tiktok.com/api/search/item/full/?keyword=%2523rstats&offset=0`

The only downside now is that the user who provides the cookies needs to be logged in.

**Comment by Jmallone** [comment]
@JBGruber 
I have a question, the offset to the next page is the value of the cursor ?
![image](https://user-images.githubusercontent.com/6977257/202517689-e7f6d1d8-34fb-4836-83df-1aca071c6774.png)

`https://www.tiktok.com/api/search/item/full/?keyword=%2523perobal&offset=36`

**Comment by JBGruber** [comment]
Using the cursor is a way better idea than what I came up with :facepalm:. I simply counted the videos that were already returned and used that number as offset.

**Comment by Jmallone** [comment]
More Insights:

A minimal Code in Python
```python
import requests

cookies = {
    'ttwid': ' ***REMOVED***',
    'sessionid': '*** REMOVED***'',
}

params = {
    'keyword': '%23rstats',
    'offset': '0',
}

response = requests.get('https://www.tiktok.com/api/search/item/full/', params=params, cookies=cookies)
response.text
```

if we remove `ttwid` in cookies this message happens:
```json 
{
  "status_code":2483,
  "status_msg":"Please login your account first",
  "log_pb":{
    "impr_id":"2022111718004042A4CCC7DE79FF1E30D0"
  }
}
```

**Comment by Jmallone** [comment]
I think you will have to use it with Delays, because here it was
```json
{
  "status_code":2484,
  "status_msg":"Too many attempts. Try again in 1 hour.",
}
```

**Comment by TimoBaeuerle** [comment]
I took the `save_hashtag_video_urls` function from `pyktok.py` as draft. 
The params must contain any `device_id`, the `keyword` and `offset`.
The `cookies` only have to contain the `ttwid`-Cookie.
The `itemList` has been renamed to `item_list`, the same applies to `hasMore` which has been renamed to `has_more`.
This works for me:
``` python
import random
import requests
import sys
import time


def get_videos_by_keyword(keyword, limit=1000):
    cursor = 0
    while cursor < limit:
        params = {
            'device_id': '1234567890123456789',
            'keyword': keyword,
            'offset': cursor,
        }
        try:
            cookies = {
                'ttwid': '1%7CPm9bTMLMzjZ48RTfSWSxsyFOpGIaDfICGUjuSUtm4ng%7C1668717040%7Cdc9c307a7f02eeae1fed06237bd2d7635c52cf583dfcde8963d1580efc90cb35'}
            response = requests.get(
                'https://www.tiktok.com/api/search/item/full/',
                params=params,
                cookies=cookies)
            data = response.json()
            videos = data['item_list']
            counter = 0
            for video in videos:
                counter = counter + 1
                #desc = video['desc']
                #created = video['createTime']
                #author = video['author']
                #views = video['stats']['playCount']
                url = 'https://tiktok.com/@' + video['author']['uniqueId'] + '/video/' + video['id']
                print(url)
                if counter >= limit:
                    break
            cursor = cursor + len(videos)
            if data["has_more"] != 1:
                break
            time.sleep(random.randint(1, 3))
        except Exception as e:
            print('Stopped at cursor="'+cursor+'"')
    print('Done.')


def main():
    args = sys.argv[1:]
    if len(args) == 2 and args[0] == '-keyword':
        keyword = args[1]
        get_videos_by_keyword(keyword)
    if len(args) == 4 and args[2] == '-limit':
        keyword = args[1]
        limit = int(args[3])
        get_videos_by_keyword(keyword, limit)
    else:
        print('You have to enter some keyword, for example: -keyword "#fun #cats"')

if __name__ == "__main__":
    args = sys.argv[1:]
    main()
```

**Comment by dfreelon** [comment]
@TimoBaeuerle Thanks for this first draft of a new function! Do you want to add it as a pull req, or are you OK with me copy-pasting the code in and crediting you in the README? If you do the former you will be listed as an official contributor, in case you care about that sort of thing.

**Comment by Jmallone** [comment]
Hi @TimoBaeuerle 
Did you resolve the `"Too many attempts"` with delays ?

**Comment by TimoBaeuerle** [comment]
Hi @Jmallone,
since i used the `device_id`-Parameter i never got this error message again. Currently i'm not sure if the delay at the end or device_id is responsible for this. Maybe i'll find out today.

**Comment by JBGruber** [comment]
"Too many attempts" was also returned for me when I sent a malformed cookie string by accident. I haven't seen it since even without pauses between requests (but I only requested a couple 1000 videos so far for testing).

**Comment by Jmallone** [comment]
@TimoBaeuerle let me know what you find afterward :)

 @JBGruber  Interesting observation, in my tests i sent a complete _Cookie_ parameters and after a few requests it simply "_burned_" the cookies and stopped working and this `"Too many attempts"` started to appear.

**Comment by dfreelon** [comment]
@TimoBaeuerle If it's OK with you, I'd like to make extensive revisions to your code before I merge it back in--I realized it's possible to pull not only URLs but also other metadata with each call to `search/item/full`, but it will require me to rethink other pieces of `pyktok` first. So it will likely take a few days, but I'll credit you in the README when I push the changes, unless you object for whatever reason.

**Comment by JBGruber** [comment]
For inspiration, these are the fields I pull. vpluck just means to return NA if the field doesn't exist in the json and to check the returned type (e.g., integer):

```
  tibble::tibble(
    video_id              = vpluck(json[[entries]], "video", "id"),
    video_timestamp       = video_timestamp,
    video_url             = vpluck(json[[entries]], "video", "downloadAddr"),
    video_length          = vpluck(json[[entries]], "video", "duration", val = "integer"),
    video_title           = vpluck(json[[entries]], "desc"),
    video_diggcount       = vpluck(json[[entries]], "stats", "diggCount", val = "integer"),
    video_sharecount      = vpluck(json[[entries]], "stats", "shareCount", val = "integer"),
    video_commentcount    = vpluck(json[[entries]], "stats", "commentCount", val = "integer"),
    video_playcount       = vpluck(json[[entries]], "stats", "playCount", val = "integer"),
    video_description     = vpluck(json[[entries]], "desc"),
    video_is_ad           = vpluck(json[[entries]], "isAd", val = "logical"),
    author_name           = author_name,
    author_followercount  = vpluck(json[[entries]], "authorStats", "followerCount", val = "integer"),
    author_followingcount = vpluck(json[[entries]], "authorStats", "followingCount", val = "integer"),
    author_heartcount     = vpluck(json[[entries]], "authorStats", "heartCount", val = "integer"),
    author_videocount     = vpluck(json[[entries]], "authorStats", "videoCount", val = "integer"),
    author_diggcount      = vpluck(json[[entries]], "authorStats", "diggCount", val = "integer")
  )
```

**Comment by dfreelon** [comment]
@JBGruber Thanks--my idea is to build out a separate function that pulls all the metadata fields that can be used either for a single video or for the results of a `search/item/full` request. That will minimize the number of requests to the TikTok server and speed up runtime... trouble is finding time to actually write out the code...

**Comment by azickri** [comment]
Hey.. Thanks for great research and work..
I'm currently researching the Tiktok API, and I found out recently, the API I'm using `(https://m.tiktok.com/api/challenge/item_list/)` doesn't work anymore.

I want to ask, is it possible to specify the return data per page with the `search/item/full` API? I've tried using the cursor but it doesn't work.

**Comment by dfreelon** [comment]
@azickri We're working on it, see upthread...

**Comment by azickri** [comment]
@dfreelon, thats great.. If I found a solution, can I share it here?

**Comment by dfreelon** [comment]
@azickri Sure thing, although I have a pretty good idea of how I want to do it, so I may borrow bits of your code rather than integrating it intact, if that's OK

**Comment by TimoBaeuerle** [comment]
> @TimoBaeuerle If it's OK with you, I'd like to make extensive revisions to your code before I merge it back in--I realized it's possible to pull not only URLs but also other metadata with each call to `search/item/full`, but it will require me to rethink other pieces of `pyktok` first. So it will likely take a few days, but I'll credit you in the README when I push the changes, unless you object for whatever reason.

Thats ok for me, thanks ;)

**Comment by stefanuq** [comment]
Hi All, thanks for finding a solution so fast! If I am not mistaken the latest changes in the TikTok API broke also the save_video_comments() function as well. Today I was trying to find a solution but it looks like that now we have to supply additional parameters like X-Bogus which are URL specific. If we change any of the other parameters (e.g. cursor) X-Bogus has to be changed as well somehow else we start to get empty responses.

**Comment by Jmallone** [comment]
Another error message that happened from trying to catch too much
```json
{
  "status_msg":"You have reached the maximum number of searched today.",
  "log_pb":{"impr_id":"2022111811254781019205416127D860D2"},
  "status_code":2484
}
```

even set `deviceId` and `delays`, @TimoBaeuerle  did this ever happen to you in you code?

**Comment by dfreelon** [comment]
@stefanuq Well in my defense I did try to warn y'all... I'll look into it and try to have some workable solutions by early next week. In the meantime, anyone is free to post working code here at any time, and I'll credit you if I end up using it.

**Comment by ccshit** [comment]
@Jmallone you need 2~ sec delay between offsets and 10 to 20 between search and you can run it 24/7

**Comment by dfreelon** [comment]
OK, I looked into this over the weekend and have a few observations:

- as @stefanuq noted, TikTok has stepped up their security around comment retrieval. Comments are not stored in the page source, and while the JSON object stored inside each video page contain a field called `comments`, it's been blank for every video I've checked.
- I've figured out two ways to pull comments using Selenium-based browser emulation:

1. Pull the comments directly from the emulated source using something like BeautifulSoup, or
2. Capture the relevant XHR request to `/api/comment/list/`, resend the request with all necessary URL params, and capture the results.

I hesitate to implement anything using Selenium for several reasons:

- Installation is complex and OS-dependent.
- It's slow.
- Getting more than 20 comments would probably require multiple Selenium requests, which compounds the slowness problem.
- TikTok [is apparently releasing a research API next year](https://twitter.com/TikTokComms/status/1593332329048440833), so I kinda want to wait and see what it can do before investing lots of time in rigging together a janky comment pipeline only to have it superseded by something much better.

But if anyone figures out anything faster for comments between now and then, LMK and I'll consider implementing it.

**Comment by Jmallone** [comment]
@dfreelon Nice observations.

The problem with waiting for tiktok to do something about it is not knowing what date it will release this official api.

**Comment by dfreelon** [comment]
@Jmallone I'm willing to wait and see in the short term (also because I have other commitments...) but I will at least fix the search function, likely over the next few days

**Comment by TimoBaeuerle** [comment]
@Jmallone I have never seen this error message. The bot I'm building is still under development, so maybe i will see more errors in production.

**Comment by dfreelon** [comment]
OK, just pushed out new functions that can pull from `search/item/full` and get comments initially visible on a video page. Try it out and LMK if you encounter problems... also the new version is not available on PyPI yet, will do that later tonight.

**Comment by dfreelon** [comment]
OK, the latest version is now up on PyPI, so I'm going to close this until someone finds something wrong with it...

**Comment by mandys** [comment]
Has anyone observed that this search isn't exactly same as the hashtag search ?
eg: tiktok.com/tag/<mytag> will give all entries with that tag

but, this end point is giving me -
https://us.tiktok.com/api/search/item/full/?keyword=#votigo&offset=0

For "votigo" keyword ( something less popular ), I see results for
vertigo
veriligo
vitiligo
virgo
voti

This is doing an actual search for anything that remotely matches the keyword.

Any ideas on how to do an absolute match ?

**Comment by azickri** [comment]
Anybody have same issue?
I try hit API **(tiktok.com/api/search/full)** with full request Cookie, but response is

```
{
 status_msg: 'Please login your account first',
 log_pb: { impr_id: '202211240158570102450591401C07BBFC' },
 status_code: 2483
}
```

**Comment by dfreelon** [comment]
@mandys I should point out that it's fairly easy to pull the first 15 videos displayed on a hashtag search. I will probably write a function to do this at some point, but right now you can do something like:

```python

import pyktok as pyk

ui = pyk.get_tiktok_json('https://www.tiktok.com/tag/uidesign')
#then parse through the data in ui['ItemModule']
```

Not nearly as good as before, but better than nothing.

**Comment by azickri** [comment]
Thats great, I will use this method if the API doesn't work.. Thanks for advice..

**Comment by dfreelon** [comment]
> @mandys I should point out that it's fairly easy to pull the first 15 videos displayed on a hashtag search. I will probably write a function to do this at some point, but right now you can do something like:
> 
> ```python
> import pyktok as pyk
> 
> ui = pyk.get_tiktok_json('https://www.tiktok.com/tag/uidesign')
> #then parse through the data in ui['ItemModule']
> ```
> 
> Not nearly as good as before, but better than nothing.

OK I did this, see new function `save_tiktok_multi_page` which works with hashtag, user, and music pages

**Comment by dfreelon** [comment]
@idksomethinggeneric If you've been running it all day, my guess is TT might be throttling your usage. You can troubleshoot this by plugging any video URL into `get_tiktok_json` and inspecting the resulting JSON object. It should be quite large, but if it's small or otherwise conveys a message like this:

```python
{
  "status_code":2484,
  "status_msg":"Too many attempts. Try again in 1 hour.",
}
```

...you should probably give it some time.

**Comment by JBGruber** [comment]
Have you gone back to the tiktok website?
You should be logged in and you sometimes get a captcha you need to solve. Only then your cookies are valid to make requests. The api annoyingly almost always returns 200.

**Comment by azickri** [comment]
@JBGruber, of course.. i was check to tiktok.com, and copy new cookie but same result.
Are you have same issue or work normally?

**Comment by dfreelon** [comment]
@azickri @JBGruber My tests are indicating the same thing has happened to `search/item/full` as to `/challenge/item_list/` before it--it's requiring the full set of fields, including `X-Bogus`, to deliver a valid response. If anyone has evidence to the contrary, please post it, otherwise `save_tiktok_multi_page` can be used as a partial replacement.

Broadly, it looks like the methods tied to TT's hidden APIs are slowly becoming unusable from a programmatic standpoint. Fortunately, the methods that pull from the JSON embedded in TT webpages still work for now, but they could vanish at any time too...

**Comment by TimoBaeuerle** [comment]
@dfreelon `search/item/full` changed. TT seems to work on an official api.
Is this documentation new? -> https://developers.tiktok.com/

I will look for a solution during this week.

**Comment by dfreelon** [comment]
@TimoBaeuerle That page is not new--it contains info on TT's current API, which doesn't allow for data collection. The placeholder page for the data collection API does appear to be new, and we'll have to see how it works when they release it, whenever that is.

**Comment by MartinaGranato** [comment]
@dfreelon 
Hi! I tried to do this: pyk.save_tiktok_multi_page('https://www.tiktok.com/@tiktok',save_video=False,save_metadata=True,browser_name='chrome')

but there's an error:
BrowserCookieError: Failed to find Chrome cookie

How can I solve this? Thank you!

**Comment by dfreelon** [comment]
@MartinaGranato The quick fix is to change line 162 in your local copy of `pyktok.py` to the following (at least it worked for me):
```python
cookies = getattr(browser_cookie3,browser_name)(domain_name='www.tiktok.com')
```
I'll roll out a proper fix for this tonight or tomorrow. Thanks for bringing it to my attention.

**Comment by MartinaGranato** [comment]
@dfreelon I've done the upgrade to 0.0.13 version, but when I do :

import pyktok as pyk
 
the error is:
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by dfreelon** [comment]
Hi, need the full traceback. Also you should make sure you're logged in to TikTok in whatever browser you are using in the `browser_name` parameter for whatever function you're trying to use.

**Comment by MartinaGranato** [comment]
TypeError                                 Traceback (most recent call last)
[<ipython-input-13-a502f1240ca9>](https://localhost:8080/#) in <module>
----> 1 import pyktok as pyk

6 frames
[/usr/local/lib/python3.8/dist-packages/pyktok/__init__.py](https://localhost:8080/#) in <module>
----> 1 from .pyktok import *

[/usr/local/lib/python3.8/dist-packages/pyktok/pyktok.py](https://localhost:8080/#) in <module>
     38            'Cache-Control': 'max-age=0',
     39            'Connection': 'keep-alive'}
---> 40 cookies = browser_cookie3.load()
     41 url_regex = '(?<=\.com/)(.+?)(?=\?|$)'
     42 

[/usr/local/lib/python3.8/dist-packages/browser_cookie3/__init__.py](https://localhost:8080/#) in load(domain_name)
    903     for cookie_fn in [chrome, chromium, opera, brave, edge, vivaldi, firefox, safari]:
    904         try:
--> 905             for cookie in cookie_fn(domain_name=domain_name):
    906                 cj.set_cookie(cookie)
    907         except BrowserCookieError:

[/usr/local/lib/python3.8/dist-packages/browser_cookie3/__init__.py](https://localhost:8080/#) in safari(cookie_file, domain_name)
    894     pass in a domain name to only load cookies from the specified domain
    895     """
--> 896     return Safari(cookie_file, domain_name).load()
    897 
    898 def load(domain_name=""):

[/usr/local/lib/python3.8/dist-packages/browser_cookie3/__init__.py](https://localhost:8080/#) in __init__(self, cookie_file, domain_name)
    733         self.__domain_name = domain_name
    734         self.__buffer = None
--> 735         self.__open_file(cookie_file)
    736         self.__parse_header()
    737 

[/usr/local/lib/python3.8/dist-packages/browser_cookie3/__init__.py](https://localhost:8080/#) in __open_file(self, cookie_file)
    743         if cookie_file is None:
    744             cookie_file = expand_paths(self.safari_cookies,'osx')
--> 745         if not os.path.exists(cookie_file):
    746             raise BrowserCookieError('Can not find Safari cookie file')
    747         self.__buffer = open(cookie_file, 'rb')

[/usr/lib/python3.8/genericpath.py](https://localhost:8080/#) in exists(path)
     17     """Test whether a path exists.  Returns False for broken symbolic links"""
     18     try:
---> 19         os.stat(path)
     20     except (OSError, ValueError):
     21         return False

TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by MartinaGranato** [comment]
@dfreelon now I'm using Python 3.9, but I have another error: ---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[6], line 1
----> 1 import pyktok as pyk

ModuleNotFoundError: No module named 'pyktok'

**Comment by dfreelon** [comment]
Well you might need to reinstall it... that's a pretty basic error.

**Comment by MartinaGranato** [comment]
@dfreelon Are there other dipendencies to install? I haven't fixed the error yet :( I have already installed beautiful soup 4, selenium, browser cookie3, requests, web driver manager, numpy, pandas.
Before you you made the changes, I was able to do the import

**Comment by dfreelon** [comment]
All the dependencies are listed in the README, but your error indicates that the module is either not installed or installed incorrectly. Here are some things to try:

```
pip uninstall pyktok
pip install pyktok
```

If that doesn't work, I would try inspecting your Python folder, specifically the subfolder `\Lib\site-packages\pyktok`, which should be there. Then you should be able to `os.chdir` into the subfolder `pyktok` inside that folder, where you should find the pyktok.py file. Importing from there should at least get you around the `ModuleNotFoundError`.

**Comment by MartinaGranato** [comment]
@dfreelon  if I switch to /usr/local/lib/python3.9/dist-packages/pyktok, the error is:
ModuleNotFoundError: No module named 'browser_cookie3'

if I switch to /usr/local/lib/python3.9/dist-packages/browser_cookie3 the error is:
ModuleNotFoundError: No module named 'pyktok'

**Comment by dfreelon** [comment]
You can try to install the previous version to see if it fixes your import problem:
```
pip uninstall pyktok
pip install pyktok==0.0.12
```
But that would likely lead you back to your original problem, albeit with Python 3.9 installed so it could work?

You can also try to run it in Python in a regular terminal (Terminal for Mac or PowerShell for Win) and see if that makes a difference.

**Comment by dfreelon** [comment]
I should also let you know most of pyktok's functions probably won't work on Google Colab because `browser_cookie3` requires Chrome or Firefox to be installed. It should work locally with Jupyter though.

**Comment by MartinaGranato** [comment]
@dfreelon the import works with Jupyter, version 0.0.13, but with:

pyk.save_tiktok_multi_page('https://www.tiktok.com/@tiktok',save_video=False,save_metadata=True,browser_name='chrome')
the error is:
The function encountered a downstream error and did not deliver any data, which happens periodically (not sure why). Please try again later.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[21], line 1
----> 1 pyk.save_tiktok_multi_page('https://www.tiktok.com/@tiktok',save_video=False,save_metadata=True)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pyktok\pyktok.py:218, in save_tiktok_multi_page(tiktok_url, save_video, save_metadata, metadata_fn, browser_name)
    212 def save_tiktok_multi_page(tiktok_url, #can be a user, hashtag, or music URL
    213                            save_video=False,
    214                            save_metadata=True,
    215                            metadata_fn='',
    216                            browser_name=None):
    217     tt_json = get_tiktok_json(tiktok_url,browser_name)
--> 218     data_loc = tt_json['ItemModule']
    219     regex_url = re.findall('(?<=www\.)(.+?)(?=\?|$)',tiktok_url)[0]
    220     video_fn = regex_url.replace('/','_') + '.mp4'

TypeError: 'NoneType' object is not subscriptable



with: pyk.save_tiktok('https://www.tiktok.com/@tiktok/video/7106594312292453675?is_copy_url=1&is_from_webapp=v1',True,'video_data.csv','chrome')

the error is:
KeyError                                  Traceback (most recent call last)
Cell In[24], line 1
----> 1 pyk.save_tiktok('https://www.tiktok.com/@tiktok/video/7106594312292453675?is_copy_url=1&is_from_webapp=v1',True,'video_data.csv','chrome')

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pyktok\pyktok.py:189, in save_tiktok(video_url, save_video, metadata_fn, browser_name)
    187 regex_url = re.findall('(?<=\.com/)(.+?)(?=\?|$)',video_url)[0]
    188 video_fn = regex_url.replace('/','_') + '.mp4'
--> 189 tt_video_url = tt_json['ItemList']['video']['preloadList'][0]['url']
    190 headers['referer'] = 'https://www.tiktok.com/'
    191 tt_video = requests.get(tt_video_url,allow_redirects=True,headers=headers)

KeyError: 'ItemList'

**Comment by dfreelon** [comment]
@MartinaGranato Please read through the solutions posted here: https://github.com/dfreelon/pyktok/issues/10
