### ISSUE TITLE
'TikTokApi' object has no attribute 'browser'

### ISSUE THREAD

**Issue by MuLIAICHI** [dfreelon/pyktok#61]
Hello guys, I'm running through this issue :
'TikTokApi' object has no attribute 'browser'

Any solution?

**Comment by dfreelon** [comment]
Please provide all the code you used, pyktok version, and full traceback...

**Comment by MuLIAICHI** [comment]
my problem was solved i uninstalled and re-install playwright.

**Comment by meiragilb** [comment]
having the same issue -- currently in playwright version 1.47.0. Should I downgrade (if so what's the easiest way to do that on Terminal, commands from [here](https://github.com/microsoft/playwright/issues/15049) are not working for me)

**Comment by dfreelon** [comment]
https://github.com/davidteather/TikTok-Api/issues/1172
