### ISSUE TITLE
An error occurred: Failed to find Firefox cookie file

### ISSUE THREAD

**Issue by MuLIAICHI** [dfreelon/pyktok#65]
Hello, any idea about the error?
Thanks

**Comment by dfreelon** [comment]
Do you have Firefox installed? Have you tried with another browser (e.g. Chrome or the others supported by `browser_cookie3`, or perhaps with no browser specified per the README?

**Comment by MuLIAICHI** [comment]
Yes i do have Firefox installed.
It's worked before just fine but now i get that error.
I will try with other browser cuz i have both edge and chrome and reply back.
I will no browser as well.

**Comment by dfreelon** [comment]
Closed due to lack of activity.
