### ISSUE TITLE
Issue with save_tiktok_comments

### ISSUE THREAD

**Issue by meiragilb** [dfreelon/pyktok#68]
Hi! Love the package -- however, when I try to pull comments, I get this error from the save_tiktok_comments function:
RuntimeError: asyncio.run() cannot be called from a running event loop

I tried modifying the function to address the issue but couldn't figure it out, or just created more issues... Thanks in advance! 

<img width="1123" alt="Screenshot 2024-10-21 at 9 07 34 AM" src="https://github.com/user-attachments/assets/a22ac021-4faa-44ba-9258-ba313046f9da">

**Comment by dfreelon** [comment]
Hi, please see possible solutions here: https://github.com/dfreelon/pyktok/issues/67

**Comment by dfreelon** [comment]
Closed due to lack of activity.
