### ISSUE TITLE
Help: Is there any similar package available in NodeJS 

### ISSUE THREAD

**Issue by srinutamada** [dfreelon/pyktok#70]
I want to implement Tiktok video download functionality in NodeJS. I tested in Python with this module and solving what we are expecting. But our application completely in NodeJS and Python is not allowed. So, can you help in finding similar package in NodeJS?

**Comment by dfreelon** [comment]
No idea--I suggest doing some searching, and if not, using Pyktok as a guide to code up a NodeJS port. The video downloading is probably the easiest part.
